"""Build creative/transition-atlas.md from docs/transitions/data.json.

The JSON is the source of truth for the 24 narrative transitions. The live
page with looping demos is docs/transitions/index.html.

Usage: python tools/build_transitions.py
"""
import json, os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "docs", "transitions", "data.json")
OUT = os.path.join(ROOT, "creative", "transition-atlas.md")
LIVE = "https://tugrawork-creator.github.io/saas-motion-kit/transitions/"

FAMILIES = [
    ("cut", "Cut", "The edit does the work. No overlap and no wipe: the match between the last frame of A and the first frame of B carries the meaning."),
    ("carry", "Carry", "Something survives the change. An object, a word, a cursor or a line walks from one scene into the next and becomes part of it."),
    ("camera", "Camera", "Move the lens, not the layers. Push through, whip, pull back or slide in depth, so the viewer travels between scenes."),
    ("mask", "Mask", "One scene opens a window onto the next. The window's shape is the message: the logo, a word, the subject, a strip."),
    ("material", "Material", "The frame is made of something. Paper folds, ink bleeds, pixels sort and glass bends: a tactile handoff."),
    ("time", "Time", "Bend the clock. Freeze, rewind, ramp or tick through time, so the transition itself says 'earlier', 'later' or 'again'."),
]
TONES = {"calm", "trustworthy", "urgent", "playful", "premium", "technical", "warm", "bold", "mysterious", "celebratory", "nostalgic"}
KEYS = ["id", "name", "family", "energy", "tones", "what", "when", "avoid", "recipe", "hyperframes"]


def check(items):
    errors, seen = [], set()
    for t in items:
        tid = t.get("id", "?")
        missing = [k for k in KEYS if k not in t]
        if missing:
            errors.append(f"{tid}: missing {', '.join(missing)}")
            continue
        if tid in seen:
            errors.append(f"{tid}: duplicate id")
        seen.add(tid)
        if t["family"] not in dict((f, n) for f, n, _ in FAMILIES):
            errors.append(f"{tid}: unknown family '{t['family']}'")
        if t["energy"] not in (1, 2, 3):
            errors.append(f"{tid}: energy must be 1, 2 or 3")
        bad = [x for x in t["tones"] if x not in TONES]
        if bad:
            errors.append(f"{tid}: tones outside the fixed set: {', '.join(bad)}")
    return errors


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def main():
    items = json.load(open(SRC, encoding="utf-8"))
    errors = check(items)
    if errors:
        sys.exit("data.json problems:\n  " + "\n  ".join(errors))

    lines = [
        "# Transition atlas",
        "",
        "<!-- Generated by tools/build_transitions.py from docs/transitions/data.json. Edit the JSON, then rerun. -->",
        "",
        f"**Live page with looping demos: [{LIVE}]({LIVE})**",
        "",
        "HyperFrames already ships the stock transitions (crossfade, blur crossfade, push, zoom-through, circle iris, blinds and the shader set).",
        "A good film repeats two or three of those as its rhythm. This atlas holds the other kind: "
        f"{len(items)} **narrative transitions** that carry meaning from one scene into the next.",
        "",
        "How to use it:",
        "",
        "1. **Keep a quiet base.** Plain hard cuts can carry the in-between beats. Log them as `motif:cut` in the ledger so the audit knows they are deliberate, and never let a flashy transition become the default.",
        "2. **Spend narrative ones where the story turns:** the hook, the reveal, the proof moment, the CTA. Pick the one whose meaning matches that cut.",
        "3. **Never twice.** Use each atlas transition once per film, and don't put two from the same family back to back.",
        "",
        "Energy runs from ●○○ (calm) to ●●● (high). Tones use a fixed vocabulary: " + ", ".join(sorted(TONES)) + ".",
        "Every entry in `data.json` also has a one-line description and a seek-safe GSAP recipe (transform, opacity, clip-path and filter only, explicit `fromTo`).",
        "",
    ]
    for fam, name, desc in FAMILIES:
        rows = [t for t in items if t["family"] == fam]
        if not rows:
            continue
        lines += [f"## {name}", "", desc, "", "| Name | Energy | Tones | When | Avoid | HyperFrames |", "|---|---|---|---|---|---|"]
        for t in rows:
            energy = "●" * t["energy"] + "○" * (3 - t["energy"])
            lines.append(
                f"| **{cell(t['id'])} {cell(t['name'])}** | {energy} | {cell(', '.join(t['tones']))} | {cell(t['when'])} | {cell(t['avoid'])} | {cell(t['hyperframes'])} |"
            )
        lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote creative/transition-atlas.md with {len(items)} transitions")


if __name__ == "__main__":
    main()
