"""Turn your motion history into a one-page report: what you keep reaching for, and what to try next.

Usage:
  python tools/history_report.py ~/.motion-ledger.json -o motion-history.html

The history file is written by `variety_audit.py --append`. The report lists every film, counts the
transitions, entrances, eases and components you used, and shows the atlas transitions and gallery
themes you have never used, ranked as "try next". It is a single self-contained HTML file.
"""
import argparse, glob, html, json, os, re
from collections import Counter

ROOT = os.path.join(os.path.dirname(__file__), "..")
e = html.escape


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower().replace("motif:", "")).strip("-")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("history")
    ap.add_argument("-o", "--out", default="motion-history.html")
    a = ap.parse_args()
    films = json.load(open(os.path.expanduser(a.history), encoding="utf-8")).get("films", [])
    atlas = json.load(open(os.path.join(ROOT, "docs", "transitions", "data.json"), encoding="utf-8"))
    themes = [json.load(open(f, encoding="utf-8")) for f in sorted(glob.glob(os.path.join(ROOT, "docs", "themes", "data", "*.json")))]

    tr = Counter(slug(x) for f in films for x in f.get("transitions", []))
    en = Counter(slug(x) for f in films for x in f.get("entrances", []))
    ea = Counter(x for f in films for x in f.get("eases", []))
    comps = [(f["name"], c) for f in films for c in f.get("new_components", [])]
    used_themes = {str(t).zfill(3) for f in films for t in f.get("themes", [])}
    atlas_unused = [t for t in atlas if slug(t["name"]) not in tr]
    fam_used = Counter(t["family"] for t in atlas if slug(t["name"]) in tr)
    fams = ["cut", "carry", "camera", "mask", "material", "time"]
    # try next: unused transitions from the least-used families first
    atlas_unused.sort(key=lambda t: (fam_used.get(t["family"], 0), -t.get("energy", 1)))
    theme_next = [t for t in themes if t["id"] not in used_themes][:8]

    def bars(counter, top=10):
        if not counter:
            return "<p class='muted'>nothing recorded yet</p>"
        m = max(counter.values())
        return "".join(f"<div class='bar'><span>{e(k)}</span><i style='width:{100 * v / m:.0f}%'></i><b>{v}</b></div>" for k, v in counter.most_common(top))

    rows = "".join(f"<tr><td>{e(f.get('date', ''))}</td><td>{e(f['name'])}</td><td>{len(f.get('transitions', []))}</td><td>{e(', '.join(f.get('new_components', [])) or '—')}</td><td>{e(', '.join(f.get('themes', [])) or '—')}</td></tr>" for f in reversed(films))
    fam_html = "".join(f"<div class='fam'><b>{fam}</b><span>{fam_used.get(fam, 0)}</span></div>" for fam in fams)
    next_tr = "".join(f"<li><b>{e(t['name'])}</b> <span class='muted'>· {e(t['family'])} · {e(', '.join(t.get('tones', [])))}</span><br>{e(t.get('when', ''))}</li>" for t in atlas_unused[:8])
    next_th = "".join(f"<li><a href='https://tugrawork-creator.github.io/saas-motion-kit/{e(t['file'])}'>{t['id']} · {e(t['name'])}</a><br><span class='muted'>{e(t.get('summary', ''))}</span></li>" for t in theme_next)

    page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Motion history</title><style>
:root{{--ink:#0E1726;--muted:#5A6475;--paper:#F6F5F1;--teal:#0FA3A3;--coral:#FF5A4E;--line:rgba(14,23,38,.12)}}
@media (prefers-color-scheme:dark){{:root{{--ink:#EDEFF3;--muted:#9AA3B2;--paper:#0F141C;--line:rgba(255,255,255,.12)}}}}
*{{box-sizing:border-box;margin:0}}body{{background:var(--paper);color:var(--ink);font:15px/1.5 system-ui,sans-serif;padding:40px 20px}}
main{{max-width:1080px;margin:0 auto}}h1{{font:600 34px/1.1 Georgia,serif}}h2{{font:600 13px system-ui;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);margin:32px 0 12px}}
.muted{{color:var(--muted)}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:20px}}
.card{{border:1px solid var(--line);border-radius:14px;padding:18px}}.bar{{display:grid;grid-template-columns:150px 1fr 30px;gap:10px;align-items:center;margin:6px 0}}
.bar i{{height:10px;border-radius:10px;background:var(--teal)}}.bar span{{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
.fams{{display:flex;gap:10px;flex-wrap:wrap}}.fam{{border:1px solid var(--line);border-radius:12px;padding:10px 14px;display:flex;gap:10px}}.fam span{{color:var(--coral);font-weight:700}}
table{{width:100%;border-collapse:collapse}}td,th{{text-align:left;padding:8px;border-bottom:1px solid var(--line);vertical-align:top}}li{{margin:8px 0}}a{{color:var(--teal)}}
</style></head><body><main>
<h1>Motion history</h1><p class="muted">{len(films)} film(s) · generated by saas-motion-kit/tools/history_report.py</p>
<h2>Transition families you've used</h2><div class="fams">{fam_html}</div>
<div class="grid"><div><h2>Transitions</h2><div class="card">{bars(tr)}</div></div><div><h2>Entrances</h2><div class="card">{bars(en)}</div></div><div><h2>Eases</h2><div class="card">{bars(ea)}</div></div></div>
<div class="grid"><div><h2>Try next: transitions you've never used</h2><div class="card"><ul>{next_tr or "<li>You've used them all. Invent a new one.</li>"}</ul></div></div>
<div><h2>Try next: themes you haven't used</h2><div class="card"><ul>{next_th}</ul></div></div></div>
<h2>Components you invented</h2><div class="card">{"".join(f"<div>{e(c)} <span class='muted'>· {e(n)}</span></div>" for n, c in comps) or "<p class='muted'>none recorded yet</p>"}</div>
<h2>Films</h2><div class="card"><table><tr><th>Date</th><th>Film</th><th>Cuts</th><th>New components</th><th>Themes</th></tr>{rows}</table></div>
</main></body></html>"""
    open(a.out, "w", encoding="utf-8").write(page)
    print("wrote", a.out)


if __name__ == "__main__":
    main()
